#!/usr/bin/env python
import json
import pathlib
import sys
import zipfile


def die(*args):
    print(*args, file=sys.stderr)
    sys.exit(1)


def fixmd5(obj, dir):
    md5 = obj["md5"]
    obj["md5"] = f"projects/{file.name}/project/{dir}/{md5}"


if len(sys.argv) != 2:
    die("Usage: unzip <myfile.sjr>")
root = pathlib.Path(__file__).parent
projects = root / "static" / "projects"
projects.mkdir(exist_ok=True)
file = pathlib.Path(sys.argv[1])
outdir = projects / file.name
if outdir.exists():
    die(f"{outdir} already exists")
with zipfile.ZipFile(file) as myzip:
    myzip.extractall(outdir)

datafile = outdir / "project" / "data.json"
data = json.loads(datafile.read_text())
fixmd5(data["thumbnail"], "thumbnails")
for page in data["json"].values():
    if not isinstance(page, dict):
        continue
    fixmd5(page, "backgrounds")
    for character in page.values():
        if not isinstance(character, dict):
            continue
        fixmd5(character, "characters")
datafile.write_text(json.dumps(data))
